package database

import (
	"backend/models"
)

func Migrate() {
	DB.Migrator().DropTable(&models.SecurityQuestion{})
	DB.Migrator().DropTable(&models.User{})
	DB.Migrator().DropTable(&models.Airline{})
	DB.Migrator().DropTable(&models.Airplane{})
	DB.Migrator().DropTable(&models.City{})
	DB.Migrator().DropTable(&models.Flight{})
	DB.Migrator().DropTable(&models.Airport{})
	DB.Migrator().DropTable(&models.Transit{})
	DB.Migrator().DropTable(&models.Seat{})
	DB.Migrator().DropTable(&models.SeatClass{})
	DB.Migrator().DropTable(&models.FlightCart{})
	DB.Migrator().DropTable(&models.FlightPromo{})
	DB.Migrator().DropTable(&models.Payment{})
	DB.Migrator().DropTable(&models.FlightTransaction{})
	DB.Migrator().DropTable(&models.FlightTransactionDetail{})
	DB.Migrator().DropTable(&models.Search{})
	DB.Migrator().DropTable(&models.Hotel{})
	DB.Migrator().DropTable(&models.HotelFacility{})
	DB.Migrator().DropTable(&models.HotelImage{})
	DB.Migrator().DropTable(&models.HotelReview{})
	DB.Migrator().DropTable(&models.HotelRating{})
	DB.Migrator().DropTable(&models.RoomType{})
	DB.Migrator().DropTable(&models.HotelRoom{})
	DB.Migrator().DropTable(&models.RoomFacility{})
	DB.Migrator().DropTable(&models.RoomImage{})
	DB.Migrator().DropTable(&models.HotelPromo{})
	DB.Migrator().DropTable(&models.HotelTransaction{})
	DB.Migrator().DropTable(&models.HotelTransactionDetail{})
	DB.Migrator().DropTable(&models.HotelCart{})

	DB.AutoMigrate(&models.SecurityQuestion{})
	DB.AutoMigrate(&models.User{})
	DB.AutoMigrate(&models.Airline{})
	DB.AutoMigrate(&models.Airplane{})
	DB.AutoMigrate(&models.City{})
	DB.AutoMigrate(&models.Flight{})
	DB.AutoMigrate(&models.Airport{})
	DB.AutoMigrate(&models.Transit{})
	DB.AutoMigrate(&models.Seat{})
	DB.AutoMigrate(&models.SeatClass{})
	DB.AutoMigrate(&models.FlightCart{})
	DB.AutoMigrate(&models.FlightPromo{})
	DB.AutoMigrate(&models.Payment{})
	DB.AutoMigrate(&models.FlightTransaction{})
	DB.AutoMigrate(&models.FlightTransactionDetail{})
	DB.AutoMigrate(&models.Search{})
	DB.AutoMigrate(&models.Hotel{})
	DB.AutoMigrate(&models.HotelFacility{})
	DB.AutoMigrate(&models.HotelImage{})
	DB.AutoMigrate(&models.HotelReview{})
	DB.AutoMigrate(&models.HotelRating{})
	DB.AutoMigrate(&models.RoomType{})
	DB.AutoMigrate(&models.HotelRoom{})
	DB.AutoMigrate(&models.RoomFacility{})
	DB.AutoMigrate(&models.RoomImage{})
	DB.AutoMigrate(&models.HotelPromo{})
	DB.AutoMigrate(&models.HotelTransaction{})
	DB.AutoMigrate(&models.HotelTransactionDetail{})
	DB.AutoMigrate(&models.HotelCart{})
}
